# Generated by Django 4.1 on 2022-08-28 17:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=200)),
                ("offer", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("days", models.CharField(max_length=2)),
                ("validUpto", models.CharField(max_length=10)),
                ("ValidOffer", models.CharField(max_length=10)),
                ("date", models.CharField(max_length=50)),
                ("desc", models.TextField()),
                ("benefits", jsonfield.fields.JSONField()),
                ("overview", jsonfield.fields.JSONField()),
            ],
        ),
    ]
